### ISSUE TITLE
Tutorials are largely outdated

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/TuringTutorials#86] opened 2020-09-23 12:27 UTC
A lot of the tutorials are unfortunately outdated due to recent improvements in MCMCChains, e.g. https://github.com/TuringLang/Turing.jl/issues/1411.

I'm opening an issue here so as to bring attention to the, well, _issue_.

**Comment by devmotion** [comment] 2020-09-23 12:35
I think maybe it would help to 1) add separate environments for different tutorials (so people can reproduce it even though it is based on an older version of some package) and 2) use CI tests and builds for the tutorials.

**Comment by torfjelde** [comment] 2020-09-23 12:36
100%. But for (2), we likely have to move away from Jupyter notebooks, right? Which, honestly, would be it's own benefit.

**Comment by torfjelde** [comment] 2020-09-23 12:39
And regarding (1), I would say that _ideally_ we'll always have the tutorials work with the most recent release of Turing, since people will look to this for inspiration when writing their own code.

Maybe we should run `Pkg.status()` at the beginning or end of every notebook too, so that people can view the dependencies.

**Comment by devmotion** [comment] 2020-09-23 12:55
> Maybe we should run `Pkg.status()` at the beginning or end of every notebook too, so that people can view the dependencies.

That's how it is done in SciML: https://github.com/SciML/SciMLTutorials.jl An appendix is added automatically to every tutorial which shows the packages and Julia version that was used to run it

**Comment by torfjelde** [comment] 2020-09-23 12:56
> That's how it is done in SciML

Nice :+1:  And they use `jmd` as the "base" file?

**Comment by devmotion** [comment] 2020-09-23 13:10
Yes. And then notebook, HTML, and PDF files are generated with Weave.

**Comment by torfjelde** [comment] 2020-09-23 13:23
Super-dope. Would it be a good idea to just try and duplicate their approach?

**Comment by devmotion** [comment] 2020-09-23 13:27
Yes, I think that would be great. In particular also thinking about https://github.com/SciML/RebuildAction which we use over at SciML to rebuild tutorials automatically (together with CompatHelper for individual environments this helps to figure out any possible issues).

**Comment by torfjelde** [comment] 2020-09-23 13:36
Yeah I just noticed that; awesome stuff! Cool, well I'm very down for doing that.

**Comment by cpfiffer** [comment] 2020-09-23 16:19
All of this is a great idea. I hate the way the tutorials currently work -- they're difficult to write in, difficult to automate, and often out-of-date. Switching to a more general `jmd` approach is something I'm all for.

**Comment by trappmartin** [comment] 2020-09-23 18:34
Super cool idea.

**Comment by torfjelde** [comment] 2020-09-25 04:10
I've now updated all the tutorials to work with the new system (which is in a separate branch `jmd-staging`, which we'll merge into master when everything is ready for a full update).

Do have a look:) We also need an updated script to publish the tutorials. One approach could be to just generate the markdown from the `jmd` file and then use the current Jekyll setup. Maybe that's a good place to start?

**Comment by devmotion** [comment] 2020-09-25 08:44
> One approach could be to just generate the markdown from the jmd file and then use the current Jekyll setup. Maybe that's a good place to start?

Yes, I think that's what we should do (at least initially). IMO we should not update too many things in one step :slightly_smiling_face:

**Comment by torfjelde** [comment] 2020-09-28 16:47
@cpfiffer I might have some questions for you about the documentation setup later, because right now I'm trying to run it locally but using a different branch of TuringTutorials, and I swear I'm loosing hair as I type. It for some reason refuses to render the the pages, despite the markdown files being available in `_tutorials/` on the top-level (I messed around with the `copy_tutorials` method to do so). It's on the `jmd-staging` branch if  you want to have a go yourself. You generate markdown just by doing
```sh
julia --project -e "using Pkg; Pkg.instantiate(); using TuringTutorials; TuringTutorials.weave_folder(\"introduction\", (:github, ))"
```
while in the project folder.

**Comment by cpfiffer** [comment] 2020-09-28 18:13
Do the rendered markdown files have YAML headers? Because otherwise they won't render. The old tutorials code would handle this automatically:

https://github.com/TuringLang/TuringTutorials/blob/38257ab7036575c63113a5b5556c8cd5fd20cb31/weave-examples.jl#L27

**Comment by torfjelde** [comment] 2020-09-28 19:12
Aaah, that might be it

**Comment by torfjelde** [comment] 2020-10-07 16:36
Btw, a small update: I can get the tutorials to render but the formatting is completely broken. Honestly don't understand why, as the output is standard markdown.

**Comment by devmotion** [comment] 2020-10-07 16:43
Do you have a reproducible example?

**Comment by torfjelde** [comment] 2020-10-07 16:50
Well, it's quite annoying to replicate but here it is:
1. `] dev TuringTutorials` and checkout `tor/jmd-weaving`
2. Go to `~/.julia/dev/TuringTutorials` and run `julia --project -e "using TuringTutorials; TuringTutorials.weave_folder("introduction", (:github, ))"` for testing
3. Change the `md_path` in `copy_tutorial` in `Turing/docs/make-utils.jl` to `HOME/.julia/dev/TuringTutorials` (you have to replace `HOME` manually)
4. `julia --project make.jl`
5. `bundle exec jekyll serve`

**Comment by devmotion** [comment] 2020-10-07 17:03
Should it be `tor/jmd-files`? I can't find `tor/jmd-weaving`

**Comment by torfjelde** [comment] 2020-10-07 17:07
Nah, `tor/jmd-weaving` should be there. Alternatively, you could try `jmd-staging` which should also work.

**Comment by devmotion** [comment] 2020-10-07 20:16
I finally managed to obtain a local preview of the docs, and formatting seems to be fine? It took me a while to figure out that the new setup (or maybe just my weird way of changing `make-utils.jl`) leads to different paths, and I had to go to `http://localhost:4000/dev/tutorials/01-introduction/` instead of just following the links to the first tutorial. So math rendering and text formatting seems fine, it seems there's just some problem with the images and gifs (they are copied to the docs folders but instead of displaying them some text is shown on the page).

**Comment by devmotion** [comment] 2020-10-07 20:16
Regular code output works fine though.

**Comment by torfjelde** [comment] 2020-10-07 20:32
Really? On my end it looks super-strange. Hmm, well, that's good news!

Yeah, I think we have to change where the figures are outputed.

**Comment by torfjelde** [comment] 2020-10-08 12:32
Btw, I realized I had a mistake in the step-by-step guide above. You also need to make sure that the files are "lifted" to the top-level in `_tutorials`, i.e. `copy_tutorial` needs to be

```julia
function copy_tutorial(tutorial_path)
    isdir(tutorial_path) || mkpath(tutorial_path)
    # Clone TuringTurorials
    tmp_path = tempname()
    mkdir(tmp_path)
    # clone("https://github.com/TuringLang/TuringTutorials", tmp_path)

    # Move to markdown folder.
    md_path = joinpath("/home/tor/.julia/dev/TuringTutorials/", "markdown")

    # Copy the .md versions of all examples.
    try
        @debug(md_path)
        # recursively find files and copy to top-level in `tutorial_path`
        for (curr_dir, dirs, files) in walkdir(md_path)
            for file in files
                full_path = joinpath(md_path, curr_dir, file)
                target_path = joinpath(tutorial_path, file)
                println("Copying $full_path to $target_path")
                cp(full_path, target_path, force=true)
                if endswith(target_path, ".md")
                    # remove_yaml(target_path, "permalink")
                    fix_header_1(target_path)
                    fix_image_path(target_path)
                end
            end
        end
        index = joinpath(@__DIR__, "src/tutorials/index.md")
        cp(index, tutorial_path * "/index.md", force=true)
    catch e
        rethrow(e)
    finally
        rm(tmp_path, recursive=true)
    end
end
```

But now it works nicely for me to!

A couple of issues:
1. Stuff like `{julia; eval = false}` at the beginning of code-blocks doesn't seem to be supported by Jekyll (it's apparently supported by Github though).
2. Figures aren't referenced correctly (as @devmotion also mentioned)
3. Naming convention is different. Personally I quite like the convention from SciMl, where you have folders representing different categories. But at the same time, just to get this done asap, it might be preferable to just change the weave-process to use a flattened structure.

**Comment by torfjelde** [comment] 2020-10-08 14:45
"Fixed" (2) and (3) locally, but (1) I can't seem to be able to fix. Even tried using what's supposed to be GFM markdown parsers in Jekyll, but none of them actually handle `{julia; eval = false}` correctly.

**Comment by torfjelde** [comment] 2020-10-08 15:14
Also there's a question of whether or not we really want to change the filenames and thus the links to the tutorials, given that there probably is a fair bit of links to the tutorials out in the wild.

**Comment by devmotion** [comment] 2020-10-08 16:22
> Figures aren't referenced correctly (as @devmotion also mentioned)

> Also there's a question of whether or not we really want to change the filenames and thus the links to the tutorials, given that there probably is a fair bit of links to the tutorials out in the wild.

I guess probably the easiest might be to change the `out_dir` and set the `fig_path` arguments in the [`weave`](http://weavejl.mpastell.com/dev/usage/#Weave.weave) command.

**Comment by torfjelde** [comment] 2020-10-08 16:24
> I guess probably the easiest might be to change the out_dir and set the fig_path arguments in the weave co

Actually only need to change `out_dir`, and yeah, that's exactly what I did:)

**Comment by dataning** [comment] 2020-10-11 14:25
Hi, I am just following the step-by-step in Bayes Logistic tutorial on the Turing.jl's website. But I run into an error in the `prediction` step. Does this have anything to do with the outdated tutorial or something I miss out in the set up? I'm using Julia 1.5.2 and the latest Turing.jl. 

```
julia> predictions = prediction(test, chain, threshold)
ERROR: type AxisArray has no field value
Stacktrace:
 [1] getproperty(x::AxisArrays.AxisArray{Float64, 2, Matrix{Float64}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, Int64}}, AxisArrays.Axis{:chain, UnitRange{Int64}}}}, f::Symbol)
   @ Base ./Base.jl:33
 [2] prediction(x::Matrix{Float64}, chain::Chains{Float64, AxisArrays.AxisArray{Float64, 3, Array{Float64, 3}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, Int64}}, AxisArrays.Axis{:var, Vector{Symbol}}, AxisArrays.Axis{:chain, UnitRange{Int64}}}}, Missing, NamedTuple{(:parameters, :internals), Tuple{Vector{Symbol}, Vector{Symbol}}}, NamedTuple{(), Tuple{}}}, threshold::Float64)
   @ Main ./REPL[38]:3
 [3] top-level scope
   @ REPL[40]:1
```

**Comment by devmotion** [comment] 2020-10-17 15:09
@torfjelde Any updates on this issue?

**Comment by torfjelde** [comment] 2020-10-17 15:41
Sorry for the delay; submission deadline a couple of days ago.

> Naming convention is different. Personally I quite like the convention from SciMl, where you have folders representing different categories. But at the same time, just to get this done asap, it might be preferable to just change the weave-process to use a flattened structure.

This should be the only issue to resolve I think. It's just a question of whether we want a flat structure, and revert the names to the old one, or if we also revamp the project structure in the process.

**Comment by devmotion** [comment] 2020-10-17 15:49
IMO it would be nice to move away from the flat structure but we don't have to do this right away if it is more difficult. However, as far as I understand, it would be even simpler to not have a flat structure, and in this case I would suggest to change it as part of the updates.

As mentioned earlier, probably different webpages/Google/twitter posts/etc. still link to the tutorials using the flat structure, so it might be good to add manual redirects from the old locations for a while.

**Comment by torfjelde** [comment] 2020-10-17 16:20
> However, as far as I understand, it would be even simpler to not have a flat structure, and in this case I would suggest to change it as part of the updates.

Correct + we definitively need non-flat structure for the `jmd` files so that we can have a Project.toml file for the different tutorials. Right now we just "flatten" the structure in `copy_tutorials`, which is fine IMO. But then the "numbering" of the names doesn't make much sence, e.g. `linear-regression/01.jl` and `hidden-markov-models/01.jl` will both be moved to the same file, which of course can cause issues (stupid example, but you get the idea).

Maybe we should just have a "flat" structure in the sense that in TuringTutorials.jl we have `tutorials/01-introduction/`, `tutorials/02-linear-regression/` and then we use the directory-names as the end of the URL?

> As mentioned earlier, probably different webpages/Google/twitter posts/etc. still link to the tutorials using the flat structure, so it might be good to add manual redirects from the old locations for a while.

Great idea :+1: We should do this regardless, as I've done some renaming (which I think is justified, e.g. moving to `01` rather than `1` in the beginning of the tutorial name).

**Comment by torfjelde** [comment] 2020-10-17 16:25
> Stuff like {julia; eval = false} at the beginning of code-blocks doesn't seem to be supported by Jekyll (it's apparently supported by Github though).

Also, this is an issue. Ideally we'd have the same rendering as Github, but in the meantime I guess we just try to use regex to remove the braces from those?

**Comment by cpfiffer** [comment] 2020-10-20 20:21
For the braces, can't we just have Weave convert `.jmd` => `.md` instead? I thought this would be a requirement to get the plots and stuff generated, since we need markdown files anyway for the website.

**Comment by torfjelde** [comment] 2020-10-20 22:25
> For the braces, can't we just have Weave convert

Seems like it's considered valid markdown because this is all talking about the markdown generated using Weave.jl :confused:

**Comment by cpfiffer** [comment] 2020-10-21 00:52
Oh, my bad. I misunderstood.

**Comment by devmotion** [comment] 2020-11-21 21:58
Gentle bump - any progress on this @torfjelde? Anything that we could help with?

**Comment by torfjelde** [comment] 2020-11-21 23:11
Sorry, haven't made any progress on this, but the remaining bit is the above, i.e. I'm having trouble with the rendering of the output generated by Weave.jl. Also not particularly familiar with Jekyll, so I was trying out different rendering engines to see why Github manages to render it correctly while our engine can't. And I got super-confused because even the Github Flavoured Kramdown (https://kramdown.gettalong.org/parser/gfm.html) wouldn't even do it correctly :confused: 

So really, any help with figuring out how to do this properly would be appreciated. I'll also have another go.

**Comment by cpfiffer** [comment] 2020-11-22 18:42
I'm not sure exactly how `weave` is being called, but historically I set `weave(...; doctype="github")` which handled all the rendering crap. I ran into the same issue and it sucked.

**Comment by torfjelde** [comment] 2020-11-23 11:06
This is using `weave(...; doctype="github")`: https://github.com/TuringLang/TuringTutorials/blob/024be8669e251b3590a0eaffb2a0a1068b20d4c5/src/TuringTutorials.jl#L48-L54

So this is where it gets weird. It seems that Github supports braces at the beginning of code-blocks, e.g. `{julia}` rather than `julia`, but Jekyll doesn't (even when using GFM parser above). 

Does anyone know how e.g. SciML deals with this? Or do they just render the actual HTML directly from jmd rather than using an intermediate renderer like Jekyll?

**Comment by kescobo** [comment] 2020-11-23 14:13
> Does anyone know how e.g. SciML deals with this? Or do they just render the actual HTML directly from jmd rather than using an intermediate renderer like Jekyll?

[Looking here](https://github.com/SciML/SciMLTutorials.jl), it seems that all of the outputs are generated (regular markdown, html, ipynb) in the main repo, and the links from the README are to plain HTML ([one example](https://tutorials.sciml.ai/html/introduction/01-ode_introduction.html)) without any styling. I'm not sure if the notebooks live somewhere else too, but I haven't seen a place where they have the tutorials integrated into the docs with consistent styling the way that Turing currently does it.

Have you tried manually doing a regex find/replace (```` ^```\{julia\} ```` => ```` ```julia ````) in the markdown to see if that renders?

**Comment by torfjelde** [comment] 2020-11-23 15:26
> and the links from the README are to plain HTML (one example) without any styling

Yeah that's what I gathered too.

> Have you tried manually doing a regex find/replace (^```\{julia\} => ```julia) in the markdown to see if that renders?

Nah, and that's of course a possible solution. I just felt like there ought to be a better way :confused: The braces could also include more stuff than just `julia`, as it's used by jmd to indicate whether or not to evaluate etc. But it should still be possible to write a simple regex to find+replace.

**Comment by kescobo** [comment] 2020-11-23 16:01
> Nah, and that's of course a possible solution. I just felt like there ought to be a better way

Totally agree, was just thinking it might be good to check whether that's the _only_ thing causing issues. 

I'm a bit confused though - it looks like weave _can_ output markdown without braces (eg. [see here](https://github.com/JunoLab/Weave.jl/blob/master/examples/FIR_design.jmd)). Is it just dependent on what the input `jmd` style is?

> The braces could also include more stuff than just julia

And Weave can handle that [without braces](http://weavejl.mpastell.com/stable/usage/#Markdown-Format)

Or are you saying that Jekyll needs the braces and you can't find a way to render without them?

> But it should still be possible to write a simple regex to find+replace.

If this is something you'd like help with, I kinda love regex puzzles :-)

**Comment by torfjelde** [comment] 2020-11-23 18:53
> I'm a bit confused though - it looks like weave can output markdown without braces (eg. see here)

Okay, so that's a bit strange. Because when I used `weave(...; doctype="github")`, lines such as https://github.com/JunoLab/Weave.jl/blob/c9fc740d72dbbd2f0b950f98efedc5ab71f17e3e/examples/FIR_design.jmd#L25-L26 did indeed show up in the generated document. It _might_ be because I added braces `{...}` around the setup, but that should be supported: http://weavejl.mpastell.com/stable/chunk_options/#Syntax. 

Hmm, I'll give it another go and see if it works properly now. 

> If this is something you'd like help with, I kinda love regex puzzles :-)

Haha, I'll keep that in mind!

**Comment by devmotion** [comment] 2020-11-24 13:03
Just some random thing I discovered (but I guess I should play around with it first to get a better feeling for the problem): have you tried to use redcarpet instead of kramdown? Maybe that can handle GFM in a better way, see e.g. https://stackoverflow.com/questions/13464590/github-flavored-markdown-and-pygments-highlighting-in-jekyll/13614020#13614020.

**Comment by devmotion** [comment] 2020-11-24 16:35
I guess this looks better: https://github.com/github/jekyll-commonmark-ghpages

And I found this issue: https://github.com/gettalong/kramdown/issues/503 In the end it was resolved/circumvented with a regex :smile:

**Comment by devmotion** [comment] 2020-11-24 17:39
@torfjelde I switched to CommonMark and I couldn't observe any problems with the code blocks when following your steps in https://github.com/TuringLang/TuringTutorials/issues/86#issuecomment-705063442. Apart from the figures for which you said it is sufficient to specify `out_dir`, http://127.0.0.1:4000/dev/tutorials/01-introduction/ looked fine (somehow there's an import problem when displaying the TuringTutorials information at the bottom of the page, but maybe that's a problem with my weird local setup).

So the only changes that I applied were:
Adding
```ruby
group :jekyll_plugins do
  gem 'jekyll-commonmark'
end
```
to Turing/docs/Gemfile and replacing `markdown: kramdown` with `markdown: CommonMark` in Turing/docs/_config.yml

**Comment by torfjelde** [comment] 2020-11-24 20:20
Ah, super neat! I'll give that a go too!

**Comment by torfjelde** [comment] 2020-11-25 13:03
Okay, so the issue with `commonmark` is that the maths gets messed up  (plus we seem to lose code highlighting, though this might just be a config somewhere?) :confused: Are you not also seeing the same thing @devmotion ?

**Comment by torfjelde** [comment] 2020-11-25 13:27
Ah, so it seems that `kramdown` actually does some conversion of maths, e.g. `$$...$$` within sentences are converted into `\(...\)` while if `$$...$$` is on it's own line then is converted into `\[...\]`. `Commonmark` does nothing to these and so mathjax cannot tell the difference between inline and display maths.

**Comment by devmotion** [comment] 2020-11-25 13:43
Oh I always assumed the standard for inline math is `$...$`. Isn't that how you usually write inline math in Weave? Or is it only generated by Weave in the GFM output?

**Comment by torfjelde** [comment] 2020-11-25 13:48
I think the solution is to add:

```julia
<script>
 MathJax = {
   tex: {
     inlineMath: [['$', '$'], ['$$', '$$']]
   }
 };
</script>
```
to `docs/_includes/headers.html` and use the `CommonmarkGhPages` renderer :+1:

This way the renderer won't do anything with maths-environments (which is honestly preferable, given the "confusing" behavior of `kramdown` where it will convert the $$...$$ differently depending on context).

**Comment by torfjelde** [comment] 2020-11-26 06:57
Another rendering issue that arises:
1. Using `kramdown`, `\\` at the end of a line as used in `\begin{align} ... \end{align}`, is _correctly_ not escaped.
2. Using `commonmark`, `\\` at the end of a line as used in `\begin{align} ... \end{align}`, is escaped, thus leading to `\` instead.

Essentially none of the renders does _exactly_ what we want, but the union of the their features would have been perfect..

Anyways, this I just fixed by replacing `\\` at the end of a line in the markdown output. It's not perfect, e.g. `\begin{align} a \\ b \end{align}` will not be replaced accordingly, but at this point I don't care anymore:) On the bright side it forces the tutorial writer to format their latex nicely! 

One question though: should we maybe instead overload https://github.com/JunoLab/Weave.jl/blob/b5ba227e757520f389a6d6e0f2cacb731eab8b12/src/WeaveMarkdown/markdown.jl#L8-L17 and do the `replace` call there? This would ensure that we only perform replacements inside of latex-blocks.

**Comment by torfjelde** [comment] 2020-11-26 09:00
I've now made it so that each tutorial has it's own directory, thus allowing deps to be specified for each tutorial + it's not always that it makes sense with the previous categorisation. All of this requires some changes to `Turing/docs/make.jl` of course but minor ones.

The _final_ part is to ensure that gif's are handled correctly. At the moment, only PNGs works. I'll have another look later this week unless someone else figures this out before me :+1:

**Comment by torfjelde** [comment] 2020-11-26 09:04
Here's the branch of Turing I'm using to copy the docs over from local TuringTutorials: https://github.com/TuringLang/Turing.jl/tree/tor/doc-updates

**Comment by devmotion** [comment] 2020-11-26 09:08
> One question though: should we maybe instead overload [JunoLab/Weave.jl@`b5ba227`/src/WeaveMarkdown/markdown.jl#L8-L17](https://github.com/JunoLab/Weave.jl/blob/b5ba227e757520f389a6d6e0f2cacb731eab8b12/src/WeaveMarkdown/markdown.jl#L8-L17) and do the `replace` call there?

That would yield an additional "Method overwritten" warning? Or do you propose to make a PR to Weave?

**Comment by torfjelde** [comment] 2020-11-26 09:27
It would, but what is two warnings to a program which already has one warning? :upside_down_face: 

I'm not sure how I'd turn it into a PR for Weave. Ideally you'd be able to dispatch differently for the markdown-parsing based on the format used, e.g. `GithubMarkdown`. But unclear to me how you'd go about doing that (other than copy-pasting everything from `Markdown` and adding another thing to dispatch on).

**Comment by devmotion** [comment] 2020-12-16 10:47
Are the gif's still problematic?

**Comment by torfjelde** [comment] 2020-12-16 12:56
Yeah. In the current setup, we generate folders for each tutorial which contains the files. With the current weave-setup we put all the files in a `figures` folder. Having thought about it I think it's best to just stick with the current approach (one folder for files related to each tutorial) which is also possible with weave. But for non-png related files, we have to save by hand, e.g.

```julia
anim = @animate for i = 1:n
    # ...
end
```

together with

```julia
fname = "anim.gif"
fpath = joinpath(WEAVE[:fig_path], fname)
savefig(fpath, anim)
fpath
```

with chunk-options (http://weavejl.mpastell.com/stable/chunk_options/#Weave-Chunk-Options) `echo = false, results = "markup"`. I haven't tried this, but hopefully something like this ought to do the trick. Though it's annoying...

Also, I think I forgot to push some of my local changes which are on my computer back in Cambridge (I'm back home in Norway atm). It was only stuff to flatten the project-structure, but still.

**Comment by devmotion** [comment] 2020-12-16 13:13
Sounds like this should be fixed upstream... Maybe one could add a dispatch here https://github.com/JunoLab/Weave.jl/blob/c9fc740d72dbbd2f0b950f98efedc5ab71f17e3e/src/WeaveMarkdown/html.jl#L23-L44, similar to https://github.com/JunoLab/Weave.jl/blob/c9fc740d72dbbd2f0b950f98efedc5ab71f17e3e/src/plots.jl#L94-L110

**Comment by torfjelde** [comment] 2020-12-17 15:36
Yeah, looks like you're right. I'll have a look.

**Comment by torfjelde** [comment] 2020-12-19 03:20
Actually, is it just a matter of adding a method like https://github.com/JunoLab/Weave.jl/blob/c9fc740d72dbbd2f0b950f98efedc5ab71f17e3e/src/plots.jl#L89-L91 for `MIME"image/gif"`?

**Comment by devmotion** [comment] 2020-12-19 09:25
I thought not, since when I generated the webpage I ended up with outputs like "Plots.AnimatedPlot....". Therefore I assumed that just the type is printed when converting to markdown instead of adding the <img> tag, as implemented in the plots.jl file linked above. But maybe I'm wrong.

**Comment by theogf** [comment] 2021-03-04 14:21
Hey I thought it would be good to revive this issue as it is obviously very needed :D 
@torfjelde What still needs to be done?

**Comment by theogf** [comment] 2021-03-04 14:23
> > Maybe we should run `Pkg.status()` at the beginning or end of every notebook too, so that people can view the dependencies.
> 
> That's how it is done in SciML: [SciML/SciMLTutorials.jl](https://github.com/SciML/SciMLTutorials.jl) An appendix is added automatically to every tutorial which shows the packages and Julia version that was used to run it

To bounce back on this, we could add a little warning at the beginning of each tutorial saying "Check that you are using the correct version of Turing for this tutorial (see end of Tutorial), if it does not work with the latest version of Turing please open an issue"

**Comment by torfjelde** [comment] 2021-03-05 07:24
Sorry, I haven't been looking at this for ages now. It first got postponed because the computer I had access to here back in Norway had very limited RAM, and so it was a hassle to do any development on this. Got an upgrade recently though, so I'll have a look again :+1: 

> Hey I thought it would be good to revive this issue as it is obviously very needed :D
@torfjelde What still needs to be done?

If I remember correctly, the following issues remain:
1. How do we deal with plots? See the last couple of comments above.
2. Need to flatten the project-structure, which I already did but then left those changes in Cambridge :upside_down_face: 

But I figured out a fix to (1) this morning, so now I'll address (2) and try to generate everything; hopefully I'll have a working PR today!

**Comment by theogf** [comment] 2021-03-05 09:35
By the way, why don't we use Literate.jl instead of Weave.jl, Literate handles plots nicely I think.

**Comment by torfjelde** [comment] 2021-03-05 14:35
Hey @theogf! Yeah you, you who are now suggesting that we use Literate.jl instead of Weave.jl after I've gone through hell to get this stuff working. Shut your face.

**Comment by theogf** [comment] 2021-03-05 14:38
Hahaha can't argue with that! :laughing::laughing::laughing: (although it would be easier to switch now :eyes: )
More seriously can I help you with the branch? Is there something to modify on each tutorial?

**Comment by torfjelde** [comment] 2021-03-05 14:42
No but on a serious note, Weave.jl handles plots nicely too. But Weave.jl respects the MIME-type, and that is messed up for gifs for some reason, and so Weave.jl treats it as text rather than a file.

And more generally, I think both Weave.jl and Literate.jl are very much the same when it comes to features but Weave.jl is more mature, is under JunoLabs and thus we'd expect it to me maintained, and finally, and this is the main reason why we went with Weave.jl in the first place, jmd is a super-straightforward conversion from our current setup since we can just take the markdown files and convert to jmd while Literate.jl is a completely different approach AFAIK.

**Comment by torfjelde** [comment] 2021-03-05 14:49
> More seriously can I help you with the branch? Is there something to modify on each tutorial?

So right now I think the PRs https://github.com/TuringLang/TuringTutorials/pull/102 and https://github.com/TuringLang/TuringTutorials/pull/103 should be good to get things working. The next step is to make sure that everything renders correctly on the website (@cpfiffer pls halp). I have a working branch of Turing that manages to do this locally, but need to ensure that this is also the case for the actual website.

After all that, I think we should really just go through the tutorials to:
1. Update dependencies.
2. Make sure everything is working correctly.

**Comment by theogf** [comment] 2021-03-05 14:52
Oh ok so the idea is to work on `jmd-staging` until everything is ready and then push to master.

**Comment by torfjelde** [comment] 2021-03-05 14:53
Exactly :+1:

**Comment by cpfiffer** [comment] 2021-03-05 18:43
Plus the changes need to happen elsewhere.

**Comment by torfjelde** [comment] 2021-03-06 12:56
So the only thing that remains now is making sure that all tutorials actually work. There are some that are just failing, e.g. regression tutorial fails because of https://github.com/JuliaStats/RDatasets.jl/issues/117. I'll go through, fix the ones I can and list the ones that are still todo, then I'll make another PR.

**Comment by theogf** [comment] 2021-03-06 14:01
I will make a new PR for the BNN tutorial (I will try to include GPU support for vi this time)

**Comment by torfjelde** [comment] 2021-03-06 18:09
Another issue I'm currently running into is that the footer thingy we have at the end of the tutorials suddenly stopped working. When I do:

```shell
julia --project -e "using TuringTutorials; TuringTutorials.weave_folder(\"00-introduction\", (:github, ))"
```

it complains that `TuringTutorials` is not available which it clearly is, unless Weave is now evaluating in the file in a different scope? If so, no one sent me that memo!

**Comment by torfjelde** [comment] 2021-03-06 18:35
So seems like it actually does: https://github.com/JunoLab/Weave.jl/blob/196d4ca7ce80e65f7365642218c43a8c94d5f286/src/run.jl#L41-L42.

But how about changing

```julia
using TuringTutorials
TuringTutorials.tutorial_footer(WEAVE_ARGS[:folder],WEAVE_ARGS[:file])
```

to

```julia
isdefined(Main, :TuringTutorials) && Main.TuringTutorials.tutorial_footer(WEAVE_ARGS[:folder],WEAVE_ARGS[:file])
```

?

This way one can still `weave` the files "outside" of TuringTutorials, but it will do the right thing if TuringTutorials is exposed in `Main`.

**Comment by cpfiffer** [comment] 2021-03-06 20:51
Yeah, I love it!

**Comment by torfjelde** [comment] 2021-03-06 21:13
Wow, I don't think I've ever seen anyone _that_ enthusiastic about changing footers before! I guess it makes sense, eh Mr. Footman?
Anyways, things are running fine now. Just waiting for the diff-eq tutorial to finish bobbing and weaving then I'll make a PR with the generated markdown files?

**Comment by torfjelde** [comment] 2021-03-06 22:27
Getting there: https://github.com/TuringLang/TuringTutorials/pull/105 and https://github.com/TuringLang/TuringTutorials/pull/106.

Is there anything else that needs to be done?

**Comment by torfjelde** [comment] 2021-03-06 22:50
Could you maybe have a check that everything is fine @cpfiffer ? Just checkout the `tor/doc-updates` branch for Turing.jl and do `] add TuringTutorials#jmd-staging` to docs, then it should just work.

**Comment by torfjelde** [comment] 2021-03-06 22:51
Don't need to check every tutorial, but mainly that the setup makes sense

**Comment by cpfiffer** [comment] 2021-03-07 04:16
Looks fine to me. We can test it live by pushing the `jmd-staging` branch and then switching over from `TuringLang/turing.ml`, where the site currently lives. It'll be a good way to check to see if the site builds correctly without having to keep the site live if something is off.

**Comment by torfjelde** [comment] 2021-03-07 06:17
Sounds good!

**Comment by torfjelde** [comment] 2021-03-07 12:44
Aight, so now it's ready to go!

Need to merge https://github.com/TuringLang/TuringTutorials/pull/109 and then https://github.com/TuringLang/TuringTutorials/pull/111 for TuringTutorials, and then finally https://github.com/TuringLang/turing.ml/pull/7 over at `turing.ml`.

**Comment by torfjelde** [comment] 2021-03-15 17:56
Is there anything remaining for us to completely move over to jmd staging at this point?
AFAIK the only thing that's left-over is fixing the maths in the non-tutorial sections over at https://github.com/TuringLang/turing.ml/. Once that's done, do we just deploy to `/dev`?

**Comment by cpfiffer** [comment] 2021-03-16 00:27
Yeah, that sounds about right. I'll try to fit in the time this week to get the turing.ml stuff ready to go.

**Comment by leachim** [comment] 2021-04-07 22:56
Hey there, I have started to make some changes to the HMM Tutorial, addressing some of the issues around it. How do you re-create the markdown files after changing the jmd files? 
I have based the work off the jmd-staging branch here, hope that's all right. I thought that should be fairly up-to-date.

**Closed** 2021-04-23 23:45 UTC
