### ISSUE TITLE
Tutorial mistakes

### ISSUE THREAD

**Issue by zenon** [TuringLang/TuringTutorials#50] opened 2019-10-29 21:01 UTC
Hi. Thank you for the great tutorials. I'm just in the process of reading them, and they are a indispensable for learning to use Turing.

I try to thank you by listing any issue I found here. As we say: Leave a place as you want to encounter it. (I'm talking about the tutorial version 0.6.23)

https://turing.ml/v0.6.23/tutorials/0-introduction/

Coin Flip without Turing
1. Please mention that GR is needed for the grapics. (The animated grapic is extremely cool, and it is a joy to recreate and understand it.)
2. in the animation, the following line has a $ to much

      title = "Updated belief after $$N observations",

Coinflip with Turing
The line

     chain = sample(coinflip(data), HMC(iterations, ϵ, τ));

should be

   chain = sample(coinflip(data), HMC(ϵ, τ), iterations);

https://turing.ml/v0.6.23/tutorials/1-gaussianmixturemodel/
The following line doesnt parse

     gmm_sampler = Gibbs(100, PG(100, 1, :k), HMC(1, 0.05, 10, :μ1, :μ2))

this one does, but as I'm off the limits of my current understanding, I'm not sure it does the right thing:

    gmm_sampler = Gibbs(PG(1, :k), HMC(0.05, 10, :μ1, :μ2))

now this one is wrong (ignore if above was wrong, and this is implied)

    tchain = mapreduce(c -> sample(gmm_model, gmm_sampler,100), chainscat, 1:3);

but this works

    tchain = mapreduce(c -> sample(gmm_model, gmm_sampler,100), chainscat, 1:3);

(same disclaimer)

The picture I get is different than the one in the tutorial. (I used the same random seed.)
This makes me doubt my corrections for the gaussian mixtures. Help welcome.

That's it for today. Kind greetings!. 
z.

I

**Comment by cpfiffer** [comment] 2019-10-30 00:42
Hey, thanks for opening an issue here! 

The tutorials have still not been updated since the change in Turing's syntax with 0.7. They are on my radar and I will fix them soon -- you will probably find a handful of errors in all the tutorials. You are also welcome to open a PR in this repo to fix these as you com upon them if you're feeling particularly energetic.

As to

> Please mention that GR is needed for the grapics. (The animated grapic is extremely cool, and it is a joy to recreate and understand it.)

The issue is not that GR is required, the issue is that the Plotly backend is extremely limited. GR, PyPlot, or any of the other significantly more feature rich backends will work fine. Your case ([this issue](https://github.com/TuringLang/Turing.jl/issues/942), for those stumbling on this) is a very unique one -- most people do not have Plotly as their default backend and are highly unlikely to run into this issue.

**Comment by zenon** [comment] 2019-10-31 11:45
Hello Cameron,

thank you for the answer. I just heard that "Julia is the answer to the two language problem", and liked the idea that I don't have to install a lot. (plus, I had some issues with admin rights on one of my computers ..)

A question, can you see whether my suggested changes in the gaussian mixtures are correct?

Thanks a lot, and kind greetings, z.

**Comment by cpfiffer** [comment] 2019-10-31 13:47
Yeah, your correction to the mixture model is correct.

**Comment by cpfiffer** [comment] 2019-12-02 01:04
Should be addressed by #51, let me know if you find anything else strange.

**Closed by cpfiffer** 2019-12-02 01:04 UTC
